"use client";

import { useState } from "react";
import Link from "next/link";
import Editor from "@monaco-editor/react";
import { useToast, ToastContainer } from "@/components/ui/toast";

type Language = "typescript" | "go" | "java";

export default function JsonToCode() {
    const [json, setJson] = useState("");
    const [code, setCode] = useState("");
    const [language, setLanguage] = useState<Language>("typescript");
    const [error, setError] = useState<string | null>(null);
    const { toasts, addToast, removeToast } = useToast();

    const capitalize = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);

    const generateTypeScript = (obj: any, name: string = "Root"): string => {
        let output = `export interface ${name} {\n`;
        Object.entries(obj).forEach(([key, value]) => {
            let type = "any";
            if (typeof value === "string") type = "string";
            else if (typeof value === "number") type = "number";
            else if (typeof value === "boolean") type = "boolean";
            else if (Array.isArray(value)) {
                if (value.length > 0 && typeof value[0] === "object") {
                    type = `${capitalize(key)}[]`;
                } else if (value.length > 0) {
                    type = `${typeof value[0]}[]`;
                } else {
                    type = "any[]";
                }
            } else if (typeof value === "object" && value !== null) {
                type = capitalize(key);
            }
            output += `  ${key}: ${type};\n`;
        });
        output += "}\n\n";

        // Recurse for nested objects
        Object.entries(obj).forEach(([key, value]) => {
            if (typeof value === "object" && value !== null && !Array.isArray(value)) {
                output += generateTypeScript(value, capitalize(key));
            } else if (Array.isArray(value) && value.length > 0 && typeof value[0] === "object") {
                output += generateTypeScript(value[0], capitalize(key));
            }
        });

        return output;
    };

    const generateGo = (obj: any, name: string = "AutoGenerated"): string => {
        let output = `type ${name} struct {\n`;
        Object.entries(obj).forEach(([key, value]) => {
            let type = "interface{}";
            const fieldName = capitalize(key);

            if (typeof value === "string") type = "string";
            else if (typeof value === "number") type = Number.isInteger(value) ? "int" : "float64";
            else if (typeof value === "boolean") type = "bool";
            else if (Array.isArray(value)) {
                if (value.length > 0 && typeof value[0] === "object") {
                    type = `[]${capitalize(key)}`;
                } else if (value.length > 0) {
                    const subType = typeof value[0] === "number" ? (Number.isInteger(value[0]) ? "int" : "float64") : typeof value[0];
                    type = `[]${subType}`;
                } else {
                    type = "[]interface{}";
                }
            } else if (typeof value === "object" && value !== null) {
                type = capitalize(key);
            }

            output += `\t${fieldName} ${type} \`json:"${key}"\`\n`;
        });
        output += "}\n\n";

        // Recurse
        Object.entries(obj).forEach(([key, value]) => {
            if (typeof value === "object" && value !== null && !Array.isArray(value)) {
                output += generateGo(value, capitalize(key));
            } else if (Array.isArray(value) && value.length > 0 && typeof value[0] === "object") {
                output += generateGo(value[0], capitalize(key));
            }
        });

        return output;
    };

    const generateJava = (obj: any, name: string = "Root"): string => {
        let output = `public class ${name} {\n`;
        Object.entries(obj).forEach(([key, value]) => {
            let type = "Object";
            if (typeof value === "string") type = "String";
            else if (typeof value === "number") type = Number.isInteger(value) ? "int" : "double";
            else if (typeof value === "boolean") type = "boolean";
            else if (Array.isArray(value)) {
                if (value.length > 0 && typeof value[0] === "object") {
                    type = `List<${capitalize(key)}>`;
                } else if (value.length > 0) {
                    const subType = typeof value[0] === "string" ? "String" : typeof value[0] === "number" ? (Number.isInteger(value[0]) ? "Integer" : "Double") : "Object";
                    type = `List<${subType}>`;
                } else {
                    type = "List<Object>";
                }
            } else if (typeof value === "object" && value !== null) {
                type = capitalize(key);
            }

            output += `    private ${type} ${key};\n`;
        });

        // Getters and Setters omitted for brevity, but fields are there
        output += "}\n\n";

        // Recurse
        Object.entries(obj).forEach(([key, value]) => {
            if (typeof value === "object" && value !== null && !Array.isArray(value)) {
                output += generateJava(value, capitalize(key));
            } else if (Array.isArray(value) && value.length > 0 && typeof value[0] === "object") {
                output += generateJava(value[0], capitalize(key));
            }
        });

        return output;
    };

    const handleConvert = (inputJson: string, lang: Language) => {
        setJson(inputJson);
        setError(null);
        if (!inputJson.trim()) {
            setCode("");
            return;
        }

        try {
            const parsed = JSON.parse(inputJson);
            let generated = "";
            if (lang === "typescript") generated = generateTypeScript(parsed);
            else if (lang === "go") generated = generateGo(parsed);
            else if (lang === "java") generated = generateJava(parsed);
            setCode(generated);
        } catch (e: any) {
            setError("Invalid JSON: " + e.message);
            setCode("");
        }
    };

    const handleCopy = (text: string) => {
        if (!text) return;
        navigator.clipboard.writeText(text);
        addToast("Copied to clipboard!", "success");
    };

    return (
        <div className="flex min-h-screen flex-col bg-zinc-950 p-6 font-sans text-zinc-100">
            <ToastContainer toasts={toasts} removeToast={removeToast} />
            <div className="mb-6 flex items-center justify-between">
                <h1 className="text-2xl font-light tracking-wide text-zinc-200">JSON to Code</h1>
                <Link
                    href="/"
                    className="rounded-lg bg-zinc-900 border border-zinc-800 px-4 py-2 text-sm font-medium text-zinc-300 transition-all hover:bg-zinc-800 hover:text-white hover:border-zinc-700"
                >
                    Back to Home
                </Link>
            </div>

            <div className="flex flex-col gap-6 h-[85vh]">

                {/* Language Selector */}
                <div className="flex justify-center">
                    <div className="flex items-center gap-2 rounded-lg bg-zinc-900/50 p-1 border border-zinc-800/50">
                        {(["typescript", "go", "java"] as Language[]).map((lang) => (
                            <button
                                key={lang}
                                onClick={() => { setLanguage(lang); handleConvert(json, lang); }}
                                className={`px-4 py-2 rounded-md text-sm font-medium transition-all capitalize ${language === lang ? "bg-zinc-100 text-zinc-900" : "text-zinc-400 hover:text-zinc-200"
                                    }`}
                            >
                                {lang}
                            </button>
                        ))}
                    </div>
                </div>

                <div className="flex flex-col lg:flex-row gap-6 flex-1 min-h-0">
                    {/* Input */}
                    <div className="flex flex-1 flex-col gap-2">
                        <div className="flex items-center justify-between">
                            <h2 className="text-sm font-medium text-zinc-400">JSON Input</h2>
                            <button
                                onClick={() => handleCopy(json)}
                                className="text-xs text-blue-400 hover:text-blue-300"
                            >
                                Copy JSON
                            </button>
                        </div>
                        <div className="flex-1 overflow-hidden rounded-xl border border-zinc-800 bg-zinc-900 relative">
                            <Editor
                                height="100%"
                                defaultLanguage="json"
                                theme="vs-dark"
                                value={json}
                                onChange={(val) => handleConvert(val || "", language)}
                                options={{ minimap: { enabled: false }, fontSize: 13, padding: { top: 16 } }}
                            />
                            {error && (
                                <div className="absolute bottom-4 left-4 right-4 bg-red-900/90 text-red-100 px-4 py-2 rounded-lg text-sm border border-red-500/50">
                                    {error}
                                </div>
                            )}
                        </div>
                    </div>

                    {/* Output */}
                    <div className="flex flex-1 flex-col gap-2">
                        <div className="flex items-center justify-between">
                            <h2 className="text-sm font-medium text-zinc-400">Generated {capitalize(language)}</h2>
                            <button
                                onClick={() => handleCopy(code)}
                                className="text-xs text-blue-400 hover:text-blue-300"
                            >
                                Copy Code
                            </button>
                        </div>
                        <div className="flex-1 overflow-hidden rounded-xl border border-zinc-800 bg-zinc-900">
                            <Editor
                                height="100%"
                                defaultLanguage={language === "typescript" ? "typescript" : language === "go" ? "go" : "java"}
                                theme="vs-dark"
                                value={code}
                                options={{ readOnly: true, minimap: { enabled: false }, fontSize: 13, padding: { top: 16 } }}
                            />
                        </div>
                    </div>
                </div>

            </div>
        </div>
    );
}
